version: "3.7"

services:
  api:
    build: server
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  app:
    build: client
    ports:
      - "3000:3000"
  db:
    image: mongo
    ports:
      - "27017:27017"
  cache:
    image: redis
    ports:
      - "6379:6379"